"""Changed username to name in user table.

Revision ID: 103dee7289a3
Revises: 6ed75a607380
Create Date: 2024-05-18 12:49:41.838238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103dee7289a3'
down_revision = '6ed75a607380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
